version: '3'
services:
  model:
    volumes:
      - ./model:/model
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=prediction.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=5001'
    command: flask run --host=0.0.0.0 --port=5001

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: energeek_app
      POSTGRES_USER: ener
      POSTGRES_PASSWORD: geek

  energapp:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=energApp
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    depends_on:
      - db
      - model